language: node_js

node_js:
  - "6"
services:
  
before_install:
  - travis_wait npm install

cache:
  - node_modules

script: 
  - npm run test
  - npm run client-test

after_success:
  - npm run coverage