export default {
  GET_ALL_USERS: 'GET_ALL_USERS',
  REGISTER_NEW_USER: 'REGISTER_NEW_USER',
  LOGIN_USER: 'LOGIN_USER',
  CREATE_USER_GROUP: 'CREATE_USER_GROUP',
  GET_USER_GROUP: 'GET_USER_GROUP'
};
